/**
 * Prompt assembly (Spec 03 §3): deterministic tool order, a frozen system block
 * with `cache_control` ephemeral, history rebuilt from persisted blocks, and the
 * volatile context appended as a `role:'system'` message at the end of `messages`.
 */
import type { Block, ChatMessage, Effort, ModelId } from '@vingsforge/shared';
import { orderedTools, type ToolDefinition } from '../tools/schemas.js';
import type { StreamRequest } from './client.js';

/** Default model and limits (Spec 03 §2). */
export const DEFAULT_MODEL: ModelId = 'claude-opus-4-8';
export const DEFAULT_EFFORT: Effort = 'high';
export const DEFAULT_MAX_TOKENS = 64_000;

/** SDK content-block params we emit (kept loose; SDK 0.68 predates some fields). */
type AnthropicContentParam = Record<string, unknown>;
interface AnthropicMessageParam {
  role: 'user' | 'assistant';
  content: AnthropicContentParam[];
}

/** Inputs needed to render a turn's prompt. */
export interface PromptInput {
  /** Canonical model id; falls back to {@link DEFAULT_MODEL}. */
  model?: ModelId;
  /** Output effort; falls back to {@link DEFAULT_EFFORT}. */
  effort?: Effort;
  /** Frozen system text: app prompt + project AGENTS.md/systemPromptExtra (Spec 03 §3). */
  system: string;
  /** Persisted prior turns, oldest first (Spec 02). */
  history: ChatMessage[];
  /** The new user text for this turn. */
  userText: string;
  /** Volatile context (date, runtime mode) injected as a trailing system message. */
  volatileContext?: string;
  /** Override the tool set; defaults to the deterministic built-ins (Spec 04). */
  tools?: readonly ToolDefinition[];
  /** Max output tokens; defaults to {@link DEFAULT_MAX_TOKENS}. */
  maxTokens?: number;
}

/**
 * Build the tools array sent to the model. Definitions are already sorted by
 * name (Spec 04 §2) so the prefix stays cache-stable; we only project them to
 * the wire shape the API expects.
 */
export function buildTools(tools: readonly ToolDefinition[] = orderedTools): AnthropicContentParam[] {
  return tools.map((t) => ({
    name: t.name,
    description: t.description,
    input_schema: t.input_schema,
  }));
}

/**
 * Build the system field. A single text block carrying the frozen prompt with a
 * `cache_control` breakpoint on the last (only) block, so tools+system cache
 * together (Spec 03 §3). No timestamps/IDs here — those go in `messages`.
 */
export function buildSystem(system: string): AnthropicContentParam[] {
  return [{ type: 'text', text: system, cache_control: { type: 'ephemeral' } }];
}

/**
 * Map one persisted block to its Anthropic content-param, or `undefined` to skip.
 *
 * `sameModel` tells whether the turn that produced this block was generated by
 * the same model as the current request. Thinking blocks (and their signatures)
 * only validate on a same-model replay (Spec 03 §2, §4; Spec 08 §4), so when the
 * model differs — or is unknown — they are dropped rather than re-sent, which
 * would otherwise 400 and break the whole turn (engine.ts L143-145).
 */
function blockToParam(block: Block, sameModel: boolean): AnthropicContentParam | undefined {
  switch (block.kind) {
    case 'text':
      return { type: 'text', text: block.text };
    case 'thinking':
      // Re-attach thinking verbatim (with signature) so same-model replay is
      // accepted by the API (Spec 03 §4, Spec 08 §4). On a model switch the
      // signature no longer validates, so drop the block entirely.
      if (!sameModel) return undefined;
      return block.signature === undefined
        ? { type: 'thinking', thinking: block.text }
        : { type: 'thinking', thinking: block.text, signature: block.signature };
    case 'tool_use':
      return { type: 'tool_use', id: block.callId, name: block.tool, input: block.input };
    case 'tool_result':
      return {
        type: 'tool_result',
        tool_use_id: block.callId,
        content: serializeToolOutput(block.output),
        is_error: block.isError,
      };
    default: {
      const exhaustive: never = block;
      void exhaustive;
      return undefined;
    }
  }
}

/** Tool output goes back as a string content (objects are JSON-encoded). */
export function serializeToolOutput(output: unknown): string {
  if (typeof output === 'string') return output;
  try {
    return JSON.stringify(output);
  } catch {
    return String(output);
  }
}

/**
 * Rebuild the `messages` array from persisted history (Spec 03 §3). Each stored
 * turn becomes one message preserving its full block list (text/thinking/tool_use
 * for assistant, tool_result/text for user). The new user turn is appended, then
 * the volatile context as a trailing `role:'system'` message (Opus 4.8).
 */
export function buildMessages(input: PromptInput): AnthropicMessageParam[] {
  const messages: AnthropicMessageParam[] = [];
  const currentModel = input.model ?? DEFAULT_MODEL;

  for (const turn of input.history) {
    // A turn replays its thinking only when it was produced by the model that
    // will receive this request. An unknown turn model is treated as a switch
    // (drop thinking) — a missing signature can't validate on the active model
    // (Spec 03 §2, Spec 08 §4; Chat.modelOverride switch — Spec 03 accept #4).
    const sameModel = turn.model !== undefined && turn.model === currentModel;
    const content = turn.blocks
      .map((block) => blockToParam(block, sameModel))
      .filter((c): c is AnthropicContentParam => c !== undefined);
    if (content.length > 0) {
      messages.push({ role: turn.role, content });
    }
  }

  messages.push({ role: 'user', content: [{ type: 'text', text: input.userText }] });

  if (input.volatileContext !== undefined && input.volatileContext.length > 0) {
    // role:'system' at the tail keeps the cached prefix intact (Spec 03 §3).
    messages.push({
      role: 'system' as 'user',
      content: [{ type: 'text', text: input.volatileContext }],
    });
  }

  return messages;
}

/**
 * Assemble the full streaming request in render order `tools → system → messages`
 * (Spec 03 §3). Uses adaptive thinking and the effort knob (Spec 03 §2).
 */
export function buildRequest(input: PromptInput): StreamRequest {
  return {
    model: input.model ?? DEFAULT_MODEL,
    max_tokens: input.maxTokens ?? DEFAULT_MAX_TOKENS,
    thinking: { type: 'adaptive', display: 'summarized' },
    output_config: { effort: input.effort ?? DEFAULT_EFFORT },
    tools: buildTools(input.tools),
    system: buildSystem(input.system),
    messages: buildMessages(input),
  };
}
