/**
 * Schema definition and version-based migrations (Spec 08 §3/§5).
 * Migrations are ordered and idempotent; the runner applies every step whose
 * version is greater than the current `schema_version` and bumps it atomically.
 */
import type { Database } from 'better-sqlite3';

/** Latest schema version shipped by this build. */
export const CURRENT_SCHEMA_VERSION = 3;

export interface Migration {
  version: number;
  up(db: Database): void;
}

/** v1 — initial schema (Spec 08 §3). */
const v1: Migration = {
  version: 1,
  up(db) {
    db.exec(`
      CREATE TABLE IF NOT EXISTS projects (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        workspace_kind TEXT NOT NULL,
        workspace_path TEXT NOT NULL,
        runtime_id TEXT NOT NULL DEFAULT 'local',
        default_model TEXT,
        system_prompt_extra TEXT,
        permission_policy TEXT,
        created_at TEXT NOT NULL,
        last_opened_at TEXT
      );

      CREATE TABLE IF NOT EXISTS chats (
        id TEXT PRIMARY KEY,
        project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
        title TEXT NOT NULL,
        model_override TEXT,
        runtime_override TEXT,
        archived INTEGER NOT NULL DEFAULT 0,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
      );

      CREATE TABLE IF NOT EXISTS messages (
        id TEXT PRIMARY KEY,
        chat_id TEXT NOT NULL REFERENCES chats(id) ON DELETE CASCADE,
        role TEXT NOT NULL,
        blocks TEXT NOT NULL,
        usage TEXT,
        created_at TEXT NOT NULL,
        seq INTEGER NOT NULL
      );

      CREATE TABLE IF NOT EXISTS runtimes (
        id TEXT PRIMARY KEY,
        label TEXT NOT NULL,
        ssh TEXT NOT NULL,
        daemon TEXT NOT NULL,
        api_key_location TEXT NOT NULL,
        auth_token TEXT
      );

      CREATE TABLE IF NOT EXISTS settings (
        key TEXT PRIMARY KEY,
        value TEXT NOT NULL
      );

      CREATE INDEX IF NOT EXISTS idx_messages_chat_seq ON messages(chat_id, seq);
      CREATE INDEX IF NOT EXISTS idx_chats_project ON chats(project_id);
    `);
  },
};

/**
 * v2 — record which model produced each message (Spec 08 §4). Needed so replay
 * can drop `thinking` from turns generated by a different model than the chat's
 * current one. Nullable: legacy rows predate the column.
 */
const v2: Migration = {
  version: 2,
  up(db) {
    const hasModel = db
      .prepare<[], { name: string }>(`PRAGMA table_info(messages)`)
      .all()
      .some((c) => c.name === 'model');
    if (!hasModel) {
      db.exec(`ALTER TABLE messages ADD COLUMN model TEXT;`);
    }
  },
};

/**
 * v3 — per-runtime daemon auth token (Spec 05 §2). The app presents it on the
 * daemon WebSocket handshake and the daemon rejects connections without it, so
 * loopback reachability alone can't drive the daemon on a shared VPS. Nullable:
 * legacy rows predate the column (re-install regenerates the token).
 */
const v3: Migration = {
  version: 3,
  up(db) {
    // `runtimes` may not exist on very old DBs; PRAGMA returns empty rows then,
    // so `hasToken` is false but there's no table to ALTER — skip in that case
    // (v1's `CREATE TABLE ... IF NOT EXISTS` already includes the column).
    const columns = db
      .prepare<[], { name: string }>(`PRAGMA table_info(runtimes)`)
      .all();
    const tableExists = columns.length > 0;
    const hasToken = columns.some((c) => c.name === 'auth_token');
    if (tableExists && !hasToken) {
      db.exec(`ALTER TABLE runtimes ADD COLUMN auth_token TEXT;`);
    }
  },
};

/** All migrations, ascending by version. */
export const MIGRATIONS: readonly Migration[] = [v1, v2, v3];

/** Read the persisted schema version (0 if never initialised). */
export function readSchemaVersion(db: Database): number {
  const row = db
    .prepare<[], { value: string }>(
      `SELECT value FROM settings WHERE key = 'schema_version'`,
    )
    .get();
  return row ? Number(row.value) : 0;
}

/**
 * Apply pending migrations inside a single transaction and persist the new version.
 * Safe to call on every boot (idempotent). Returns the resulting version.
 */
export function runMigrations(db: Database): number {
  // The settings table must exist before we can read/write the version.
  db.exec(
    `CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);`,
  );

  const apply = db.transaction(() => {
    const current = readSchemaVersion(db);
    let applied = current;
    for (const migration of [...MIGRATIONS].sort((a, b) => a.version - b.version)) {
      if (migration.version > current) {
        migration.up(db);
        applied = migration.version;
      }
    }
    if (applied !== current) {
      db.prepare(
        `INSERT INTO settings (key, value) VALUES ('schema_version', @v)
         ON CONFLICT(key) DO UPDATE SET value = @v`,
      ).run({ v: String(applied) });
    }
    return applied;
  });

  return apply();
}
